# Post classification Experiment using Scikit learn

* Date 20/02/18
* Dylan Butler

## Task
The overall task of this experiment is to create a trained classifier to correctly classify whether or not a post is useful for quizes and knowledge testing of Java core concepts.

## Data
The data for this experiment consists of a manually labelled dataset of 1500 stackoverflow posts. These posts have been filtered according to the following characteristics:

* They posses the structure of either a "how-to"(procedural intent) or a "why"(casual intent) type of question
* They have a minimum score of 7 (post score)
* They have not been deleted
* They have not been closed
* They have an accepted answer

After extracting this data I conducted an analysis on the resulting dataset to gain a deeper understanding of the data:

### Extracted Data insights
* Group 1 (useful for quizzes):
    * How to split a string in Java?
    * Read and convert an input stream to a string?
    * How to read all files in a folder in Java?
    * How to round a number to n decimal places in Java?
    * How to parse JSON in Java?
    * How do I declare and initialize an array in Java?
    * Why is it faster to process an unsorted array vs a sorted array
    * How do I compare strings in Java?
* Group 2 (not useful fr quizzes):
    * How do I fix android.os.NetworkOnMainThreadException?
    * How do you assert that a certain exception is thrown in JUnit 4 tests?
    * How to fix java.lang.UnsupportedClassVersionError: Unsupported major.minor version
    * How to add local jar files to a Maven project?
    * How do I set up IntelliJ IDEA for Android applications?
    * How does autowiring work in Spring?
    * How do I tell Maven to use the latest version of a dependency?
    * Unfortunately MyApp has stopped. How can I solve this?
    * Why is subtracting these two times (in 1927) giving a strange result?

### Key Findings
* Useless Q's
    * A key difference I can spot is that most of the questions that pose no use are environment, framework, related and focus on a technology that uses Java.
    * Verbs like; set-up, fix, stopped ... i.e. less java specific and more generic - used in everyday language. 
* Useful Q's
    * The useful questions seem to be following a pattern in which the main words in the questions (split, string, read, java, JSON, declare, initialize) are all words closely related to Java and programming concepts in general.  
    * The verbs/action words used in the useful q's are closely associated with java itself.
    
    
# Experiment Process

1. Chunk tags and titles and bodies into a single body
    * eliminate code snippets 
    * remove stop words
    * lemmatise each body
2. Extract the core features from the text that the algorithm can learn from
3. Train a classifier
4. Evaluate
5. Improve results

# 1) Generating the data
The format I will converting the data into for this first experiment will be flattened chunks of (tags, title and body) of each post. 

1. Remove all the code snippets from the bodys and titles of the  text --> using BeautifulSoup
2. Clean the post tags from the <[tag | tag-tag]> format --> [tag | tag tag]
3. Merge the tags, title, bodies into a single chunk
4. remove all stop words


In [2]:
import pandas 
df = pandas.read_csv('./data/procedural_casual_Q_1500_SO_Java.csv')

In [3]:
df.head()

Id  Score                                               Body  \
0  13225      8  <p>I've recently inherited a internationalized...   
1  24991     19  <p>I have defined a Java function:</p>\n\n<pre...   
2  24866     11  <p>I am using Java back end for creating an XM...   
3  25449     29  <p>I want to create a Java program that can be...   
4  26305    151  <p>I want to be able to play sound files in my...   

                                               Title  \
0  How can I refactor HTML markup out of my prope...   
1  Why can't I explicitly pass the type argument ...   
2  Is it essential that I use libraries to manipu...   
3           How to create a pluginable Java program?   
4                      How can I play sound in Java?   

                                        Tags  AnswerCount  CommentCount  \
0  <java><jsp><internationalization><struts>            4             0   
1                   <java><generics><syntax>            4             1   
2                                <java><xml>           11             0   
3       <java><plugins><plugin-architecture>            6             1   
4                              <java><audio>            9             1   

   FavoriteCount  ViewCount  OK  
0            NaN       2078   0  
1            6.0      21171   1  
2            NaN        690   0  
3           18.0      17544   1  
4           57.0     262318   1

Merge each posts body and title into a single chunk

In [8]:
df.columns[2:4]

Index(['Body', 'Title'], dtype='object')

In [10]:
#merges title and body into a single chunk
df['Title_Body_Chunk'] = df[df.columns[2:4]].apply(lambda x: ','.join(x),axis=1)

In [21]:
df.drop(['Body', 'Title'], axis=1)

Id  Score                                               Tags  \
0        13225      8          <java><jsp><internationalization><struts>   
1        24991     19                           <java><generics><syntax>   
2        24866     11                                        <java><xml>   
3        25449     29               <java><plugins><plugin-architecture>   
4        26305    151                                      <java><audio>   
5     40545683      8                           <java><mappedbytebuffer>   
6     16192410     11                                      <java><mysql>   
7        43802     60                             <java><date><calendar>   
8      8110975     19  <java><swing><colors><paintcomponent><transluc...   
9        47177    137     <java><memory><cross-platform><cpu><diskspace>   
10       64036    223                               <java><class><clone>   
11    32418456     10       <java><polymorphism><primitive><return-type>   
12    32418461      9                         <java-8><method-reference>   
13       65200    111                                        <java><jvm>   
14     1588420     16  <java><constructor><initialization><thread-saf...   
15     1589517    129     <java><svn><versioning><intellij-idea><branch>   
16     9327822      8                                    <java><android>   
17     1593074      8            <java><web-applications><maven-2><osgi>   
18     1593203     10  <java><unit-testing><maven-2><junit><annotations>   
19    17336804      8  <mysql><hibernate><java-ee><struts2><notificat...   
20    17337526    104                           <java><eclipse><upgrade>   
21    17338246      8                              <java><syntax><enums>   
22     9328252     25                     <java><multithreading><syntax>   
23     9328763      8              <java><coding-style><aop><spring-aop>   
24     1599963     11  <java><transparency><bufferedimage><javax.imag...   
25     9329283     33                             <java><spring><hsqldb>   
26     1600667     41        <java><polymorphism><override><subclassing>   
27     1601793     21   <java><eclipse><code-formatting><code-standards>   
28     9330394     47                  <java><list><random><probability>   
29     1609126     18                    <java><testing><multithreading>   
...        ...    ...                                                ...   
1469    107823     26               <java><multithreading><memory-leaks>   
1470  32495069     20                        <java><java-8><java-stream>   
1471   8151766     10  <java><exception-handling><classnotfoundexcept...   
1472   8151952     14                                    <java><android>   
1473   8157755    176                                      <java><enums>   
1474   8152393     25                      <java><crash><jvm><jvm-crash>   
1475  16301074     10              <java><netbeans><directory><jvm><jni>   
1476  24378270     14                 <java><mysql><jdbc><insert-update>   
1477    136580      8                        <java><user-interface><swt>   
1478    136308     10                           <java><eclipse><maven-2>   
1479    137212    120     <java><performance><security><random><entropy>   
1480   8164540     11       <java><string><algorithm><language-agnostic>   
1481    146576    421                               <java><static><main>   
1482   8171460     10                              <java><swing><jtable>   
1483   8171488     25  <java><android><android-activity><ipc><parcela...   
1484  32518658     12               <java><java-8><java-stream><flatmap>   
1485    147454    272                           <java><import><wildcard>   
1486    147468     66                     <java><collections><interface>   
1487    156503   1457           <java><exception><junit><junit4><assert>   
1488    156697      8                      <java><xml><oracle><encoding>   
1489  32531962      8                      <java><sorting><i

In [25]:
from bs4 import BeautifulSoup
from bs4 import Tag

In [39]:
def _remove_attrs(soup):
    for tag in soup.findAll(True): 
        tag.attrs = None
    return soup

In [51]:
#initialise a new column
df['cleaned_body_title'] = ""

# loop thorugh the data frame
for index, row in df.iterrows():
        
        #print(row.Title_Body_Chunk)
        
        soup = BeautifulSoup(row['Title_Body_Chunk'], 'html5lib')
        
        for code in soup.find_all("code"):
            code.decompose()
        cleaned = soup.get_text()
        
        #create a new column to hold the cleaned data
        df.loc[index, "cleaned_body_title"] = cleaned

In [55]:
df = df.drop(['Title', 'Body', 'Title_Body_Chunk'], axis=1)

In [56]:
df.head()

Id  Score                                       Tags  AnswerCount  \
0  13225      8  <java><jsp><internationalization><struts>            4   
1  24991     19                   <java><generics><syntax>            4   
2  24866     11                                <java><xml>           11   
3  25449     29       <java><plugins><plugin-architecture>            6   
4  26305    151                              <java><audio>            9   

   CommentCount  FavoriteCount  ViewCount  OK  \
0             0            NaN       2078   0   
1             1            6.0      21171   1   
2             0            NaN        690   0   
3             1           18.0      17544   1   
4             1           57.0     262318   1   

                                  cleaned_body_title  
0  I've recently inherited a internationalized an...  
1  I have defined a Java function:\n\n\n\nOne way...  
2  I am using Java back end for creating an XML s...  
3  I want to create a Java program that can be ex...  
4  I want to be able to play sound files in my pr...

Generate a Dataframe with only the classification and the chunk of text

In [57]:
df_new = df[['cleaned_body_title', 'OK']]

In [59]:
#df_new

# 2) Extracting Features from the documents

In [60]:
import numpy as np

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
cv = CountVectorizer()
counts = cv.fit_transform(df_new['cleaned_body_title'].values)

In [71]:
counts

<1499x8026 sparse matrix of type '<class 'numpy.int64'>'
	with 85058 stored elements in Compressed Sparse Row format>

### list all of the elements in the CountVectorizer

In [92]:
#cv.get_feature_names()

# 3) Classifying the Posts

The first classifier I will be implementing is a naive bayes classifier. Bayes theorom - each feature (in this case word counts) is independent from every other one and each one contributes to the probability that an example belongs to a particular class

## Create, Initialize and train a new MultinomialNB

In [76]:
from sklearn.naive_bayes import MultinomialNB

classifier = MultinomialNB()
#targets are the OK column in the df_new dataframe above
targets = df_new['OK'].values
#train the NB classifier
classifier.fit(counts, targets)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

### test out the classifier

In [79]:
examples = ["How do I explicitly pass the type argument to a generic Java method? I do not understand how to achieve this", "How do I generate a new eclipse project? I am trying to create a new eclipse project and I need help setting it up"]
example_counts = cv.transform(examples)
predictions = classifier.predict(example_counts)

In [80]:
predictions

array([1, 0], dtype=int64)

#### Notes on the above:

The predictor can correctly classify between the two examples that were generated using the chunk of text provided for each. 

## Pipelining - connecting the process

a pipeline can be introduced to merge both the feature extraction and classification into one operation

In [83]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', MultinomialNB())
])

pipeline.fit(df_new['cleaned_body_title'].values, df_new['OK'].values)
pipeline.predict(examples)

array([1, 0], dtype=int64)

# 4) Cross-validating the model - K-fold

At this stage in the process it is required to cross validate the model i.e. check its accuracy to ensure that it can give accurate predictions when faced with new data.

Shuffling the data to ensure that our training and test sets are balanced when we perform the 80:20 split, training:test 

In [84]:
# frac keyword - specifies the number of rows to return in the rand
# sample -> 1 returns all rows
df_new = df_new.sample(frac=1)

## create an instance of K-Fold CV

In [90]:
from sklearn.cross_validation import KFold
from sklearn.metrics import confusion_matrix, f1_score

kf = KFold(n=len(df_new), n_folds = 10)
scores = [] #holds the score for each
confusion = np.array([[0,0], [0,0]]) #initialize the confusion matrix

for train_ind, test_ind in kf:
    
    #training data(x) and classification(y)
    train_x = df_new.iloc[train_ind]['cleaned_body_title'].values
    train_y = df_new.iloc[train_ind]['OK'].values
    
    #testing training data
    test_x = df_new.iloc[test_ind]['cleaned_body_title'].values
    test_y = df_new.iloc[test_ind]['OK'].values
    
    pipeline.fit(train_x, train_y)
    predictions = pipeline.predict(test_x)
    
    confusion += confusion_matrix(test_y, predictions)
    score = f1_score(test_y, predictions, pos_label=1)
    scores.append(score)

In [91]:
print('Total posts classified:', len(df_new))
print('Score:', sum(scores)/len(scores))
print('Confusion matrix:')
print(confusion)

Total emails classified: 1499
Score: 0.806086804881
Confusion matrix:
[[744 123]
 [120 512]]
